export const POST_CREATE_POST_BEGIN = 'POST_CREATE_POST_BEGIN';
export const POST_CREATE_POST_SUCCESS = 'POST_CREATE_POST_SUCCESS';
export const POST_CREATE_POST_FAILURE = 'POST_CREATE_POST_FAILURE';
export const POST_CREATE_POST_DISMISS_ERROR = 'POST_CREATE_POST_DISMISS_ERROR';
